### PR TITLE
add evalTC and evalT to Tactic.Reflection

### PR DESCRIPTION
**Pull request by m0davis**
H/t Yorick Sijsling <yoricksijsling@gmail.com> who posted this on the agda mailing list as "Running the TC monad"

### CODE REVIEW

**Comment by UlfNorell** [comment]
`runTC` is not a very good name for this function. How about making it a macro and calling it `evalT`? You could then use it as

```agda
ex : evalT (getParameters (quote List)) ≡ 2
ex = refl
```

If you're ok with that, I could merge the pull request and then do the change.

**Comment by m0davis** [comment]
Looks good, thanks.

**Comment by m0davis** [comment]
On second thought... How about keeping runTC and renaming it to evalTC? I think I could provide a use-case in which only having evalT would be insufficient.

**Comment by UlfNorell** [comment]
I'm ok with that.

**Pull request merged**
